import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Hero } from "@/components/sections";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Transactions App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-7xl mx-auto bg-[#0F1117]">
          <Hero />
            {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
