import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Hero, Navbar } from "@/components/sections";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Transactions App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${process.env.NODE_ENV == "development" ? "debug-screens" : ""}`}>
        <main className="max-w-7xl mx-auto bg-[#0F1117]">
          <Navbar />
          {/* <Hero /> */}
            {children}
          <Footer />
        </main>
        </body>
    </html>
  );
}
